export const CONTENT_SEARCH_API_URL = String(process.env.REACT_APP_CONTENT_SEARCH_API_URL)
export const MARKETPLACE_URL = String(process.env.REACT_APP_MARKETPLACE_URL)
export const POULTRY_CAROUSELS_PAGE_URL = String(process.env.REACT_APP_POULTRY_CAROUSELS_PAGE_URL)
